scrape_interval: "10s"
collectors:
  pidstat: true
  iostat: true
  vmstat: true
  benchmark: true
  ping:
    enabled: true
    targets:
      - "localhost"
      - "127.0.0.1"
  audit:
    enabled: true
    log_path: "/var/log/kubernetes/api-audit.log"
  mtr:
    enabled: true
    targets:
      - "localhost"
      - "127.0.0.1"
